db.Restaurants.find().pretty();
db.Restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({},{_id:0,restaurant_id:1,name:1,borough:1,"address.zipcode":1}).pretty();
db.Restaurants.find({borough:"Bronx"},{name:1});
db.Restaurants.find({borough:"Bronx"},{name:1}).limit(5);
db.Restaurants.find({borough:"Bronx"},{name:1}).limit(5).skip(5);
db.Restaurants.find({"grades.score":{$gt:90}}).pretty();
db.Restaurants.find({"grades.score":{$gt:80,$lt:100}}).pretty();
db.Restaurants.find({"address.coord":{$lt:-95.754168}}).pretty();
db.Restaurants.find({$and:[{"cuisine":{$ne:"American "}},{"grades.score":{$gt:70}},{"address.coord":{$lt:-65.754168}}]}).pretty();
db.Restaurants.find({"cuisine":{$ne:"American "},"grades.score":{$gt:70},"address.coord":{$lt:-65.754168}}).pretty();
db.Restaurants.find({"cuisine":{$ne:"American "},"grades.grade":{$eq:'A'},"borough":{$ne:"Brooklyn"}}).sort({cuisine:-1}).pretty();
db.Restaurants.find({name:{$regex:/^Wil/}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({name:{$regex:/ces$/}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({name:{$regex:/Reg/i}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({$and:[{borough:"Bronx"},{cuisine:{$in:["American ","Chinese"]}}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({$or:[{borough:"Staten Island"},{borough:"Queens"},{borough:"Bronx"},{borough:"Brooklyn"}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({$nor:[{borough:"Staten Island"},{borough:"Queens"},{borough:"Bronx"},{borough:"Brooklyn"}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({"grades.score":{$lt:10}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({$and:[{$nor:[{cuisine:"American "},{cuisine:"Chinese"}],$or:[{name:{$regex:/^Wil/}}]}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty();
db.Restaurants.find({grades:{$elemMatch:{grade:"A",score:11,date:ISODate('2014-08-11T00:00:00Z')}}},{restaurant_id:1,name:1,grades:1}).pretty();
db.Restaurants.find({'grades.1.grade':"A",'grades.1.score':9,'grades.1.date':ISODate('2014-08-11T00:00:00Z')},{restaurant_id:1,name:1,grades:1}).pretty();
db.Restaurants.find({'address.coord.1':{$gte:42,$lte:52}},{restaurant_id:1,address:1,"address.coord":1}).pretty();
db.Restaurants.find().sort({name:1}).pretty();
db.Restaurants.find().sort({name:-1}).pretty();
db.Restaurants.find({},{cuisine:1,borough:1}).sort({cuisine:1,borough:-1}).pretty();
db.Restaurants.find({'address.street':{$exists:true}}).count();
db.Restaurants.find({'address.coord':{$type:'double'}}).pretty();
db.Restaurants.find({'grades.score':{$mod:[7,0]}}).pretty();
db.Restaurants.find({name:{$regex:/mon/}},{name:1,borough:1,'address.coord':1,cuisine:1}).pretty();
db.Restaurants.find({name:{$regex:/^Mad/}},{name:1,borough:1,'address.coord':1,cuisine:1}).pretty();
